// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc.team308.robot;

import edu.wpi.first.wpilibj.IterativeRobot;
import edu.wpi.first.wpilibj.Preferences;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.Scheduler;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.smartdashboard.SendableChooser;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc.team308.robot.commands.*;
import org.usfirst.frc.team308.robot.subsystems.*;

/**
 * The VM is configured to automatically run this class, and to call the
 * functions corresponding to each mode, as described in the IterativeRobot
 * documentation. If you change the name of this class or the package after
 * creating this project, you must also update the manifest file in the resource
 * directory.
 */
public class Robot extends IterativeRobot {

	Preferences prefs = Preferences.getInstance();

	SendableChooser autoChooser;

	Command autonomousCommand;

	public static OI oi;
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	public static Drivetrain drivetrain;

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	//public static Vision vision;
	public static Arm arm;
	public static Claw claw;
	public static UltraSonic ultrasonic;

	/**
	 * This function is run when the robot is first started up and should be
	 * used for any initialization code.
	 */
	public void robotInit() {
		RobotMap.init();
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
		drivetrain = new Drivetrain();

		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
		//vision = new Vision();
		arm = new Arm();
		claw = new Claw();
		ultrasonic = new UltraSonic();
		// OI must be constructed after subsystems. If the OI creates Commands
		// (which it very likely will), subsystems are not guaranteed to be
		// constructed yet. Thus, their requires() statements may grab null
		// pointers. Bad news. Don't move it.
		oi = new OI();

		autoChooser = new SendableChooser();

		autoChooser.addDefault("Drive Forward", new Autonomous3());
		autoChooser.addObject("Nothing", new DoNothing(1));
		autoChooser.addObject("Autonomous Right", new Autonomous1());
		autoChooser.addObject("Autonomous Left", new Autonomous2());

		SmartDashboard.putData("Autonomous Mode", autoChooser);
		SmartDashboard.putString("version", "1.5.0");
	}

	/**
	 * This function is called when the disabled button is hit. You can use it
	 * to reset subsystems before shutting down.
	 */
	public void disabledInit() {
	}

	public void disabledPeriodic() {
		Scheduler.getInstance().run();
	}

	public void autonomousInit() {
		// schedule the autonomous command (example)
		Globals.gyroP = prefs.getDouble("gyroP", 0.0);
		Globals.gyroI = prefs.getDouble("gyroI", 0.0);
		Globals.gyroD = prefs.getDouble("gyroD", 0.0);
		Globals.clawRotateP = prefs.getDouble("clawRotateP", 0.0);
		Globals.clawRotateI = prefs.getDouble("clawRotateI", 0.0);
		Globals.clawRotateD = prefs.getDouble("clawRotateD", 0.0);
		Globals.talonP = prefs.getDouble("talonP", 0.0);
		Globals.talonI = prefs.getDouble("talonI", 0.0);
		Globals.talonD = prefs.getDouble("talonD", 0.0);
		SmartDashboard.putNumber("gyroP", Globals.gyroP);
		SmartDashboard.putNumber("gyroI", Globals.gyroI);
		SmartDashboard.putNumber("gyroD", Globals.gyroD);
		SmartDashboard.putNumber("clawRotateP", Globals.clawRotateP);
		SmartDashboard.putNumber("clawRotateI", Globals.clawRotateI);
		SmartDashboard.putNumber("clawRotateD", Globals.clawRotateD);
		Robot.drivetrain.disablePID();
		Robot.drivetrain.setPID();
		Robot.drivetrain.enablePID();
		Robot.claw.setPID();
		Robot.arm.reset();
		Robot.claw.reset();
		autonomousCommand = (Command) autoChooser.getSelected();
		if (autonomousCommand != null) {
			autonomousCommand.start();
		}
	}

	/**
	 * This function is called periodically during autonomous
	 */
	public void autonomousPeriodic() {
		Scheduler.getInstance().run();
	}

	public void teleopInit() {
		// This makes sure that the autonomous stops running when
		// teleop starts running. If you want the autonomous to
		// continue until interrupted by another command, remove
		// this line or comment it out.
		Globals.gyroP = prefs.getDouble("gyroP", 0.0);
		Globals.gyroI = prefs.getDouble("gyroI", 0.0);
		Globals.gyroD = prefs.getDouble("gyroD", 0.0);
		Globals.clawRotateP = prefs.getDouble("clawRotateP", 0.0);
		Globals.clawRotateI = prefs.getDouble("clawRotateI", 0.0);
		Globals.clawRotateD = prefs.getDouble("clawRotateD", 0.0);
		Globals.gyrocorrection = prefs.getDouble("gyrocorrection", 0);
		SmartDashboard.putNumber("gyroP", Globals.gyroP);
		SmartDashboard.putNumber("gyroI", Globals.gyroI);
		SmartDashboard.putNumber("gyroD", Globals.gyroD);
		SmartDashboard.putNumber("clawRotateP", Globals.clawRotateP);
		SmartDashboard.putNumber("clawRotateI", Globals.clawRotateI);
		SmartDashboard.putNumber("clawRotateD", Globals.clawRotateD);
		/*Robot.drivetrain.disablePID();
		Robot.drivetrain.setPID();
		Robot.drivetrain.enablePID();
		Robot.claw.setPID();
		Robot.arm.reset();
		Robot.claw.reset();*/
		if (autonomousCommand != null) {
			autonomousCommand.cancel();
		}
	}

	/**
	 * This function is called periodically during operator control
	 */
	public void teleopPeriodic() {
		Scheduler.getInstance().run();
	}

	/**
	 * This function is called periodically during test mode
	 */
	public void testPeriodic() {
		LiveWindow.run();
	}
}
